/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AchievementId = IDL.Text;
export const Rarity = IDL.Variant({
  'epic' : IDL.Null,
  'legendary' : IDL.Null,
  'rare' : IDL.Null,
  'common' : IDL.Null,
  'uncommon' : IDL.Null,
});
export const Achievement = IDL.Record({
  'id' : AchievementId,
  'title' : IDL.Text,
  'unlocked' : IDL.Bool,
  'description' : IDL.Text,
  'isDemo' : IDL.Bool,
  'progress' : IDL.Nat,
  'requirement' : IDL.Text,
  'rarity' : Rarity,
});
export const LeaderboardEntry = IDL.Record({
  'principal' : IDL.Principal,
  'playerAlias' : IDL.Text,
  'rank' : IDL.Nat,
  'isDemo' : IDL.Bool,
  'score' : IDL.Nat,
  'stage' : IDL.Nat,
  'achievements' : IDL.Vec(AchievementId),
  'bossesDefeated' : IDL.Nat,
});
export const PlayerProfile = IDL.Record({
  'stageReached' : IDL.Nat,
  'principal' : IDL.Principal,
  'alias' : IDL.Text,
  'isDemo' : IDL.Bool,
  'achievements' : IDL.Vec(Achievement),
  'bossesDefeated' : IDL.Nat,
});
export const TokenId = IDL.Text;
export const Timestamp = IDL.Nat;
export const TokenMetric = IDL.Record({
  'staked' : IDL.Nat,
  'tokenId' : TokenId,
  'circulating' : IDL.Nat,
  'utility' : IDL.Text,
  'source' : IDL.Text,
  'lastUpdated' : Timestamp,
  'locked' : IDL.Nat,
  'isDemo' : IDL.Bool,
  'supply' : IDL.Nat,
  'burned' : IDL.Nat,
});
export const VaultEntryId = IDL.Text;
export const VaultStatus = IDL.Variant({
  'LIVE' : IDL.Null,
  'LORE' : IDL.Null,
  'IN_DEVELOPMENT' : IDL.Null,
  'COMING_SOON' : IDL.Null,
});
export const VaultCategory = IDL.Variant({
  'LORE' : IDL.Null,
  'ECONOMIC_MECHANIC' : IDL.Null,
  'GAME_MECHANIC' : IDL.Null,
});
export const VaultEntry = IDL.Record({
  'id' : VaultEntryId,
  'status' : VaultStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isDemo' : IDL.Bool,
  'category' : VaultCategory,
});
export const WorldId = IDL.Text;
export const World = IDL.Record({
  'id' : WorldId,
  'theme' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isDemo' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getPlayerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PlayerProfile)],
      ['query'],
    ),
  'getTokenMetrics' : IDL.Func([], [IDL.Vec(TokenMetric)], ['query']),
  'getVaultData' : IDL.Func([], [IDL.Vec(VaultEntry)], ['query']),
  'getWorlds' : IDL.Func([], [IDL.Vec(World)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AchievementId = IDL.Text;
  const Rarity = IDL.Variant({
    'epic' : IDL.Null,
    'legendary' : IDL.Null,
    'rare' : IDL.Null,
    'common' : IDL.Null,
    'uncommon' : IDL.Null,
  });
  const Achievement = IDL.Record({
    'id' : AchievementId,
    'title' : IDL.Text,
    'unlocked' : IDL.Bool,
    'description' : IDL.Text,
    'isDemo' : IDL.Bool,
    'progress' : IDL.Nat,
    'requirement' : IDL.Text,
    'rarity' : Rarity,
  });
  const LeaderboardEntry = IDL.Record({
    'principal' : IDL.Principal,
    'playerAlias' : IDL.Text,
    'rank' : IDL.Nat,
    'isDemo' : IDL.Bool,
    'score' : IDL.Nat,
    'stage' : IDL.Nat,
    'achievements' : IDL.Vec(AchievementId),
    'bossesDefeated' : IDL.Nat,
  });
  const PlayerProfile = IDL.Record({
    'stageReached' : IDL.Nat,
    'principal' : IDL.Principal,
    'alias' : IDL.Text,
    'isDemo' : IDL.Bool,
    'achievements' : IDL.Vec(Achievement),
    'bossesDefeated' : IDL.Nat,
  });
  const TokenId = IDL.Text;
  const Timestamp = IDL.Nat;
  const TokenMetric = IDL.Record({
    'staked' : IDL.Nat,
    'tokenId' : TokenId,
    'circulating' : IDL.Nat,
    'utility' : IDL.Text,
    'source' : IDL.Text,
    'lastUpdated' : Timestamp,
    'locked' : IDL.Nat,
    'isDemo' : IDL.Bool,
    'supply' : IDL.Nat,
    'burned' : IDL.Nat,
  });
  const VaultEntryId = IDL.Text;
  const VaultStatus = IDL.Variant({
    'LIVE' : IDL.Null,
    'LORE' : IDL.Null,
    'IN_DEVELOPMENT' : IDL.Null,
    'COMING_SOON' : IDL.Null,
  });
  const VaultCategory = IDL.Variant({
    'LORE' : IDL.Null,
    'ECONOMIC_MECHANIC' : IDL.Null,
    'GAME_MECHANIC' : IDL.Null,
  });
  const VaultEntry = IDL.Record({
    'id' : VaultEntryId,
    'status' : VaultStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isDemo' : IDL.Bool,
    'category' : VaultCategory,
  });
  const WorldId = IDL.Text;
  const World = IDL.Record({
    'id' : WorldId,
    'theme' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isDemo' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getPlayerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerProfile)],
        ['query'],
      ),
    'getTokenMetrics' : IDL.Func([], [IDL.Vec(TokenMetric)], ['query']),
    'getVaultData' : IDL.Func([], [IDL.Vec(VaultEntry)], ['query']),
    'getWorlds' : IDL.Func([], [IDL.Vec(World)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };