/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'id' : AchievementId,
  'title' : string,
  'unlocked' : boolean,
  'description' : string,
  'isDemo' : boolean,
  'progress' : bigint,
  'requirement' : string,
  'rarity' : Rarity,
}
export type AchievementId = string;
export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface LeaderboardEntry {
  'principal' : Principal,
  'playerAlias' : string,
  'rank' : bigint,
  'isDemo' : boolean,
  'score' : bigint,
  'stage' : bigint,
  'achievements' : Array<AchievementId>,
  'bossesDefeated' : bigint,
}
export interface PlayerProfile {
  'stageReached' : bigint,
  'principal' : Principal,
  'alias' : string,
  'isDemo' : boolean,
  'achievements' : Array<Achievement>,
  'bossesDefeated' : bigint,
}
export type Rarity = { 'epic' : null } |
  { 'legendary' : null } |
  { 'rare' : null } |
  { 'common' : null } |
  { 'uncommon' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export type TokenId = string;
export interface TokenMetric {
  'staked' : bigint,
  'tokenId' : TokenId,
  'circulating' : bigint,
  'utility' : string,
  'source' : string,
  'lastUpdated' : Timestamp,
  'locked' : bigint,
  'isDemo' : boolean,
  'supply' : bigint,
  'burned' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export type VaultCategory = { 'LORE' : null } |
  { 'ECONOMIC_MECHANIC' : null } |
  { 'GAME_MECHANIC' : null };
export interface VaultEntry {
  'id' : VaultEntryId,
  'status' : VaultStatus,
  'title' : string,
  'description' : string,
  'isDemo' : boolean,
  'category' : VaultCategory,
}
export type VaultEntryId = string;
export type VaultStatus = { 'LIVE' : null } |
  { 'LORE' : null } |
  { 'IN_DEVELOPMENT' : null } |
  { 'COMING_SOON' : null };
export interface World {
  'id' : WorldId,
  'theme' : string,
  'name' : string,
  'description' : string,
  'isDemo' : boolean,
}
export type WorldId = string;
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getAchievements' : ActorMethod<[], Array<Achievement>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getPlayerProfile' : ActorMethod<[Principal], [] | [PlayerProfile]>,
  'getTokenMetrics' : ActorMethod<[], Array<TokenMetric>>,
  'getVaultData' : ActorMethod<[], Array<VaultEntry>>,
  'getWorlds' : ActorMethod<[], Array<World>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'schema' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];